// <auto-generated />
using System;
using InsightsHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InsightsHub.Api.Migrations
{
    [DbContext(typeof(InsightsHubDbContext))]
    [Migration("20260330224124_AddColorAndAiNotesToOpportunity")]
    partial class AddColorAndAiNotesToOpportunity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataSourceEntityFeedbackItemEntity", b =>
                {
                    b.Property<string>("DataSourcesId")
                        .HasColumnType("text");

                    b.Property<string>("FeedbackItemsId")
                        .HasColumnType("text");

                    b.HasKey("DataSourcesId", "FeedbackItemsId");

                    b.HasIndex("FeedbackItemsId");

                    b.ToTable("FeedbackItemDataSource", (string)null);
                });

            modelBuilder.Entity("DataSourceEntityOpportunityEntity", b =>
                {
                    b.Property<string>("DataSourcesId")
                        .HasColumnType("text");

                    b.Property<string>("OpportunitiesId")
                        .HasColumnType("text");

                    b.HasKey("DataSourcesId", "OpportunitiesId");

                    b.HasIndex("OpportunitiesId");

                    b.ToTable("OpportunityDataSource", (string)null);
                });

            modelBuilder.Entity("FeedbackItemEntityTagEntity", b =>
                {
                    b.Property<string>("FeedbackItemsId")
                        .HasColumnType("text");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("FeedbackItemsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("FeedbackItemTag", (string)null);
                });

            modelBuilder.Entity("FeedbackItemEntityTeamEntity", b =>
                {
                    b.Property<string>("FeedbackItemsId")
                        .HasColumnType("text");

                    b.Property<int>("TeamsId")
                        .HasColumnType("integer");

                    b.HasKey("FeedbackItemsId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("FeedbackItemTeam", (string)null);
                });

            modelBuilder.Entity("InsightsHub.Api.Data.Entities.DataSourceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastSynced")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataSource", (string)null);
                });

            modelBuilder.Entity("InsightsHub.Api.Data.Entities.FeedbackItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AiNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsAiProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpportunityId")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId");

                    b.ToTable("FeedbackItem", (string)null);
                });

            modelBuilder.Entity("InsightsHub.Api.Data.Entities.OpportunityEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AiNotes")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Opportunity", (string)null);
                });

            modelBuilder.Entity("InsightsHub.Api.Data.Entities.SavedViewEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SavedView", (string)null);
                });

            modelBuilder.Entity("InsightsHub.Api.Data.Entities.TagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("InsightsHub.Api.Data.Entities.TeamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Team", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "property-b2b"
                        },
                        new
                        {
                            Id = 2,
                            Name = "property-b2c"
                        });
                });

            modelBuilder.Entity("OpportunityEntityTagEntity", b =>
                {
                    b.Property<string>("OpportunitiesId")
                        .HasColumnType("text");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("OpportunitiesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("OpportunityTag", (string)null);
                });

            modelBuilder.Entity("OpportunityEntityTeamEntity", b =>
                {
                    b.Property<string>("OpportunitiesId")
                        .HasColumnType("text");

                    b.Property<int>("TeamsId")
                        .HasColumnType("integer");

                    b.HasKey("OpportunitiesId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("OpportunityTeam", (string)null);
                });

            modelBuilder.Entity("DataSourceEntityFeedbackItemEntity", b =>
                {
                    b.HasOne("InsightsHub.Api.Data.Entities.DataSourceEntity", null)
                        .WithMany()
                        .HasForeignKey("DataSourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsightsHub.Api.Data.Entities.FeedbackItemEntity", null)
                        .WithMany()
                        .HasForeignKey("FeedbackItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataSourceEntityOpportunityEntity", b =>
                {
                    b.HasOne("InsightsHub.Api.Data.Entities.DataSourceEntity", null)
                        .WithMany()
                        .HasForeignKey("DataSourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsightsHub.Api.Data.Entities.OpportunityEntity", null)
                        .WithMany()
                        .HasForeignKey("OpportunitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeedbackItemEntityTagEntity", b =>
                {
                    b.HasOne("InsightsHub.Api.Data.Entities.FeedbackItemEntity", null)
                        .WithMany()
                        .HasForeignKey("FeedbackItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsightsHub.Api.Data.Entities.TagEntity", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeedbackItemEntityTeamEntity", b =>
                {
                    b.HasOne("InsightsHub.Api.Data.Entities.FeedbackItemEntity", null)
                        .WithMany()
                        .HasForeignKey("FeedbackItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsightsHub.Api.Data.Entities.TeamEntity", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InsightsHub.Api.Data.Entities.FeedbackItemEntity", b =>
                {
                    b.HasOne("InsightsHub.Api.Data.Entities.OpportunityEntity", "Opportunity")
                        .WithMany()
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("OpportunityEntityTagEntity", b =>
                {
                    b.HasOne("InsightsHub.Api.Data.Entities.OpportunityEntity", null)
                        .WithMany()
                        .HasForeignKey("OpportunitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsightsHub.Api.Data.Entities.TagEntity", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpportunityEntityTeamEntity", b =>
                {
                    b.HasOne("InsightsHub.Api.Data.Entities.OpportunityEntity", null)
                        .WithMany()
                        .HasForeignKey("OpportunitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsightsHub.Api.Data.Entities.TeamEntity", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
